<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-RDR3QR6H" failures="2" tests="3" name="Login Tests" time="8.783" errors="0" timestamp="2022-10-07T13:50:59 IST">
  <testcase classname="testcasesextent.TestClassUsingListeners" name="testFailed" time="1.205">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testcasesextent.TestClassUsingListeners.testFailed(TestClassUsingListeners.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testFailed -->
  <testcase classname="testcasesextent.TestClassUsingListeners" name="testPassed" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcasesextent.TestClassUsingListeners.testPassed(TestClassUsingListeners.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testPassed -->
  <testcase classname="testcasesextent.TestClassUsingListeners" name="testSkipped" time="0.891">
    <skipped/>
  </testcase> <!-- testSkipped -->
</testsuite> <!-- Login Tests -->
